### ISSUE TITLE
Encryption Has Changed

### ISSUE THREAD

**Issue by slipsystem** [wlan222/kisscartoon#7] opened 2016-06-05 13:12 UTC
Hey guys I think they have changed the Encrypition on the videos. 

File "kissgrab.py", line 54, in <module>
    print episode.links[0].link
IndexError: list index out of range

the array is no linksin it.

**Comment by jafrewa** [comment] 2016-06-05 13:19
Okay will take a look once I'm home

**Comment by jafrewa** [comment] 2016-06-05 21:29
```
! function(b) {
    function f() {
        g = CryptoJS.enc.Hex.parse(d);
        var b = $.ajax({
            url: /External/RSK,
            type: POST,
            async: !1
        }).responseText;
        a = CryptoJS.SHA256(b)
    }
    var g, a, d = a5e8d2e9c1721ae0e84ad660c472c1f3;
    f.prototype.decrypt = function(b) {
        var f = null;
        try {
            var d = CryptoJS.lib.CipherParams.create({
                    ciphertext: CryptoJS.enc.Base64.parse(b)
                }),
                h = CryptoJS.AES.decrypt(d, a, {
                    mode: CryptoJS.mode.CBC,
                    iv: g,
                    padding: CryptoJS.pad.Pkcs7
                });
            return f = h.toString(CryptoJS.enc.Utf8)
        } catch (c) {
            return 
        }
    }, b.$kissenc = new f
}(window)
```

I extracted this code from their website. Will try to make sense out of it tomorrow

**Comment by slipsystem** [comment] 2016-06-26 12:01
D Slee's code work on grease monkey, maybe his script will help it looks way to complicated to me

https://greasyfork.org/en/scripts/10305-kissanime-cartoon-downloader/code

HIGHWAY99 also has a addon for kodi he uses a similar way to decrypt as you do but his also needs to be updated

https://github.com/HIGHWAY99/repository.thehighway/tree/master/repo

you can find his code under 

plugin.video.kisscartoon

i am not trying to rush you you are doing an awesome job. thanks for all the excellent work

**Comment by jafrewa** [comment] 2016-06-27 18:40
The problem is that a UserScript can access the original decrypting code. I have to rewrite it in Python.

**Comment by slipsystem** [comment] 2016-08-04 16:49
if you can make sense of this I think we have a way to get it to work.  

 `#!/usr/bin/env python
"""
Kissasian and Kisscaroon decryption
Created by: Twoure
Date:       06/04/2016
Changed to Work with Kodi KissCartoon/Asian Addon 06/05/2016 PrometheusX
"""
import binascii
import pyaes
from sha2 import sha256 as SHA256

import base64

class KissDecrypt:
    def __init__(self): 
        #kissasian
        di = base64.b64decode("XzMyYjgxMmU5YTEzMjFhZTBlODRhZjY2MGM0NzIyYjNhXw==")[1:-1]
        self.derived_drama_iv = binascii.a2b_hex(di)
        #kisscartoon
        ci = base64.b64decode("X2E1ZThkMmU5YzE3MjFhZTBlODRhZDY2MGM0NzJjMWYzXw==")[1:-1]
        self.derived_cartoon_iv = binascii.a2b_hex(ci)
        
    def unpad_string(self, text, k=16):
        """
        Remove the PKCS#7 padding from a text string
        Made by https://gist.github.com/chrix2
        """
        nl = len(text)
        val = int(binascii.b2a_hex(text[-1]), 16)
        if val > k:
            raise ValueError('Input is not padded or padding is corrupt')
        l = nl - val
        return text[:l]
               
    def ensure_unicode(self, v):
        if isinstance(v, str):
            v = v.decode('utf8')
        return unicode(v)

    def decrypt(self, f, kind, r):#url=None, dh=None):
        """
        decrypt video URL input depending on what site it came from
        """
        #headers.update({'X-Requested-With': 'XMLHttpRequest', 'Content-Length': '0'})
        #r = requests.post(Common.GetBaseURL(url) + '/External/RSK', headers=headers)
        key = str(r)
        derived_key = SHA256(key).digest()
        if kind == 'drama':
            return self.decrypt_input(f, derived_key, self.derived_drama_iv)
        else:
            return self.decrypt_input(f, derived_key, self.derived_cartoon_iv)       

    def decrypt_input(self, f, key, iv):
        """decrypt video URL"""
        aes = pyaes.AESModeOfOperationCBC(key, iv)
        etb = binascii.a2b_base64(f)

        if len(etb) >= 16:
            dt = []
            for i in xrange(len(etb)/16):
                d = aes.decrypt(etb[i*(16):(i+1)*(16)])
                dt.append(d)
            r = ''.join(dt)
            r = self.unpad_string(r)
            return self.ensure_unicode(r)
        else:
            Log.Error('* KissDecrypt Error: ciphertext block is not larger than 16')
            raise ValueError('ciphertext block is not larger than 16')`

It comes from a kodi addon, I have tested it and its working.

**Comment by milezzz** [comment] 2016-08-21 23:37
REALLY hope someone better with Python can get this working.  Can also confirm the kodi code is working above.

**Comment by jafrewa** [comment] 2016-08-24 19:11
My main issue fixing this is not the decryption itself it's the part where you get a key(?) from /External/RSK

**Comment by kylewill0725** [comment] 2016-09-10 06:45
Have you tried using cfscape? I used scraper.post("http://kisscartoon.me/External/RSK") which at first returned a 404 error but upon calling again, returns the RSK key in its content property.

Example snippet:
```
rskKey = scraper.post("http://kisscartoon.me/External/RSK")
while (rskKey.status_code == 404):
       rskKey = scraper.post("http://kisscartoon.me/External/RSK")
print rskKey.content
```

**Comment by wlan222** [comment] 2016-09-10 07:19
I'm pretty positive that I'm using cfscrape for all HTTP communications in this but I can try later. Thanks for the input.

Gesendet von Yahoo Mail auf Android 
 
  Am Sa., 10. Sep. 2016 um 8:45 hat kylewill0725<notifications@github.com> Folgendes geschrieben:   
Have you tried using cfscape? I used scraper.post("http://kisscartoon.me/External/RSK") which at first returned a 404 error but upon calling again, returns the RSK key in its content property.

Example snippet:
rskKey = scraper.post("http://kisscartoon.me/External/RSK")
while (rskKey.status_code == 404):
       rskKey = scraper.post("http://kisscartoon.me/External/RSK")
print rskKey.content

**Comment by kylewill0725** [comment] 2016-09-10 19:25
Got it working. Submitted pull request.

**Comment by jafrewa** [comment] 2016-09-11 08:30
Fixed by @kylewill0725

**Closed by jafrewa** 2016-09-11 08:30 UTC
